---
language: php

os:
    - linux

php:
    - 5.6
    - 7.0

install: true

before_script:
    - travis_retry composer self-update
    - travis_retry composer install --no-interaction --prefer-source --dev

script:
    - phpunit -v --configuration .phpunit.xml --coverage-clover=coverage.xml

notifications:
  email:
    - admin@openlogiks.org
    - bismay4u@gmail.com
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/c1a23c4fe63fb3541655
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
    
after_success:
  - bash <(curl -s https://codecov.io/bash)