<?php
$classPath=array(
		"api/",
		"api/libs/",
		"plugins/modules/",
	);
$mediaPaths=array(
		"#APPROOT#userdata/",
		"#APPROOT#media/",
		"#APPROOT#css/",
		"#THEME#/",
		"media/",
		"media/#SITENAME#/",
	);
$vendorPath=array(
		"#APPROOT#plugins/",
		"#ROOT#api/",
		"#ROOT#plugins/",
		"#ROOT#pluginsDev/",
	);
$pluginPaths=array(
		"#APPROOT#plugins/",
		"#ROOT#pluginsDev/",
		"#ROOT#plugins/",
	);
?>
