<?php
/*
 * This is inspired from many of the other systems eg. Codeigniter
 * 
 * Author: Bismay Kumar Mohapatra bismay4u@gmail.com
 * Version: 1.0
 */
if(!defined('ROOT')) exit('No direct script access allowed');

if(!function_exists("getTimeZones")) {
	function getTimeZones() {
		return array(
				"Africa/Abidjan", "Africa/Accra", "Africa/Addis_Ababa", "Africa/Algiers", "Africa/Asmara", "Africa/Asmera", "Africa/Bamako", "Africa/Bangui", 
				"Africa/Banjul", "Africa/Bissau", "Africa/Blantyre", "Africa/Brazzaville", "Africa/Bujumbura", "Africa/Cairo", "Africa/Casablanca", "Africa/Ceuta", 
				"Africa/Conakry", "Africa/Dakar", "Africa/Dar_es_Salaam", "Africa/Djibouti", "Africa/Douala", "Africa/El_Aaiun", "Africa/Freetown", "Africa/Gaborone", 
				"Africa/Harare", "Africa/Johannesburg", "Africa/Juba", "Africa/Kampala", "Africa/Khartoum", "Africa/Kigali", "Africa/Kinshasa", "Africa/Lagos", 
				"Africa/Libreville", "Africa/Lome", "Africa/Luanda", "Africa/Lubumbashi", "Africa/Lusaka", "Africa/Malabo", "Africa/Maputo", "Africa/Maseru", 
				"Africa/Mbabane", "Africa/Mogadishu", "Africa/Monrovia", "Africa/Nairobi", "Africa/Ndjamena", "Africa/Niamey", "Africa/Nouakchott", "Africa/Ouagadougou",
				"Africa/Porto-Novo", "Africa/Sao_Tome", "Africa/Timbuktu", "Africa/Tripoli", "Africa/Tunis", "Africa/Windhoek", "America/Adak", "America/Anchorage", 
				"America/Anguilla", "America/Antigua", "America/Araguaina", "America/Argentina/Buenos_Aires", "America/Argentina/Catamarca", 
				"America/Argentina/ComodRivadavia", "America/Argentina/Cordoba", "America/Argentina/Jujuy", "America/Argentina/La_Rioja", "America/Argentina/Mendoza", 
				"America/Argentina/Rio_Gallegos", "America/Argentina/Salta", "America/Argentina/San_Juan", "America/Argentina/San_Luis", "America/Argentina/Tucuman", 
				"America/Argentina/Ushuaia", "America/Aruba", "America/Asuncion", "America/Atikokan", "America/Atka", "America/Bahia", "America/Bahia_Banderas", 
				"America/Barbados", "America/Belem", "America/Belize", "America/Blanc-Sablon", "America/Boa_Vista", "America/Bogota", "America/Boise", 
				"America/Buenos_Aires", "America/Cambridge_Bay", "America/Campo_Grande", "America/Cancun", "America/Caracas", "America/Catamarca", "America/Cayenne", 
				"America/Cayman", "America/Chicago", "America/Chihuahua", "America/Coral_Harbour", "America/Cordoba", "America/Costa_Rica", "America/Cuiaba", 
				"America/Curacao", "America/Danmarkshavn", "America/Dawson", "America/Dawson_Creek", "America/Denver", "America/Detroit", "America/Dominica", 
				"America/Edmonton", "America/Eirunepe", "America/El_Salvador", "America/Ensenada", "America/Fort_Wayne", "America/Fortaleza", "America/Glace_Bay", 
				"America/Godthab", "America/Goose_Bay", "America/Grand_Turk", "America/Grenada", "America/Guadeloupe", "America/Guatemala", "America/Guayaquil", 
				"America/Guyana", "America/Halifax", "America/Havana", "America/Hermosillo", "America/Indiana/Indianapolis", "America/Indiana/Knox", 
				"America/Indiana/Marengo", "America/Indiana/Petersburg", "America/Indiana/Tell_City", "America/Indiana/Vevay", "America/Indiana/Vincennes", 
				"America/Indiana/Winamac", "America/Indianapolis", "America/Inuvik", "America/Iqaluit", "America/Jamaica", "America/Jujuy", "America/Juneau", 
				"America/Kentucky/Louisville", "America/Kentucky/Monticello", "America/Knox_IN", "America/Kralendijk", "America/La_Paz", "America/Lima", 
				"America/Los_Angeles", "America/Louisville", "America/Lower_Princes", "America/Maceio", "America/Managua", "America/Manaus", "America/Marigot", 
				"America/Martinique", "America/Matamoros", "America/Mazatlan", "America/Mendoza", "America/Menominee", "America/Merida", "America/Metlakatla", 
				"America/Mexico_City", "America/Miquelon", "America/Moncton", "America/Monterrey", "America/Montevideo", "America/Montreal", "America/Montserrat", 
				"America/Nassau", "America/New_York", "America/Nipigon", "America/Nome", "America/Noronha", "America/North_Dakota/Beulah", "America/North_Dakota/Center", 
				"America/North_Dakota/New_Salem", "America/Ojinaga", "America/Panama", "America/Pangnirtung", "America/Paramaribo", "America/Phoenix", 
				"America/Port-au-Prince", "America/Port_of_Spain", "America/Porto_Acre", "America/Porto_Velho", "America/Puerto_Rico", "America/Rainy_River", 
				"America/Rankin_Inlet", "America/Recife", "America/Regina", "America/Resolute", "America/Rio_Branco", "America/Rosario", "America/Santa_Isabel", 
				"America/Santarem", "America/Santiago", "America/Santo_Domingo", "America/Sao_Paulo", "America/Scoresbysund", "America/Shiprock", "America/Sitka", 
				"America/St_Barthelemy", "America/St_Johns", "America/St_Kitts", "America/St_Lucia", "America/St_Thomas", "America/St_Vincent", "America/Swift_Current", 
				"America/Tegucigalpa", "America/Thule", "America/Thunder_Bay", "America/Tijuana", "America/Toronto", "America/Tortola", "America/Vancouver", 
				"America/Virgin", "America/Whitehorse", "America/Winnipeg", "America/Yakutat", "America/Yellowknife", "Antarctica/Casey", "Antarctica/Davis", 
				"Antarctica/DumontDUrville", "Antarctica/Macquarie", "Antarctica/Mawson", "Antarctica/McMurdo", "Antarctica/Palmer", "Antarctica/Rothera", 
				"Antarctica/South_Pole", "Antarctica/Syowa", "Antarctica/Vostok", "Arctic/Longyearbyen", "Asia/Aden", "Asia/Almaty", "Asia/Amman", "Asia/Anadyr", 
				"Asia/Aqtau", "Asia/Aqtobe", "Asia/Ashgabat", "Asia/Ashkhabad", "Asia/Baghdad", "Asia/Bahrain", "Asia/Baku", "Asia/Bangkok", "Asia/Beirut", 
				"Asia/Bishkek", "Asia/Brunei", "Asia/Calcutta", "Asia/Choibalsan", "Asia/Chongqing", "Asia/Chungking", "Asia/Colombo", "Asia/Dacca", "Asia/Damascus", 
				"Asia/Dhaka", "Asia/Dili", "Asia/Dubai", "Asia/Dushanbe", "Asia/Gaza", "Asia/Harbin", "Asia/Hebron", "Asia/Ho_Chi_Minh", "Asia/Hong_Kong", "Asia/Hovd", 
				"Asia/Irkutsk", "Asia/Istanbul", "Asia/Jakarta", "Asia/Jayapura", "Asia/Jerusalem", "Asia/Kabul", "Asia/Kamchatka", "Asia/Karachi", "Asia/Kashgar", 
				"Asia/Kathmandu", "Asia/Katmandu", "Asia/Kolkata", "Asia/Krasnoyarsk", "Asia/Kuala_Lumpur", "Asia/Kuching", "Asia/Kuwait", "Asia/Macao", "Asia/Macau", 
				"Asia/Magadan", "Asia/Makassar", "Asia/Manila", "Asia/Muscat", "Asia/Nicosia", "Asia/Novokuznetsk", "Asia/Novosibirsk", "Asia/Omsk", "Asia/Oral", 
				"Asia/Phnom_Penh", "Asia/Pontianak", "Asia/Pyongyang", "Asia/Qatar", "Asia/Qyzylorda", "Asia/Rangoon", "Asia/Riyadh", "Asia/Saigon", "Asia/Sakhalin", 
				"Asia/Samarkand", "Asia/Seoul", "Asia/Shanghai", "Asia/Singapore", "Asia/Taipei", "Asia/Tashkent", "Asia/Tbilisi", "Asia/Tehran", "Asia/Tel_Aviv", 
				"Asia/Thimbu", "Asia/Thimphu", "Asia/Tokyo", "Asia/Ujung_Pandang", "Asia/Ulaanbaatar", "Asia/Ulan_Bator", "Asia/Urumqi", "Asia/Vientiane", 
				"Asia/Vladivostok", "Asia/Yakutsk", "Asia/Yekaterinburg", "Asia/Yerevan", "Atlantic/Azores", "Atlantic/Bermuda", "Atlantic/Canary", 
				"Atlantic/Cape_Verde", "Atlantic/Faeroe", "Atlantic/Faroe", "Atlantic/Jan_Mayen", "Atlantic/Madeira", "Atlantic/Reykjavik", "Atlantic/South_Georgia", 
				"Atlantic/St_Helena", "Atlantic/Stanley", "Australia/ACT", "Australia/Adelaide", "Australia/Brisbane", "Australia/Broken_Hill", "Australia/Canberra", 
				"Australia/Currie", "Australia/Darwin", "Australia/Eucla", "Australia/Hobart", "Australia/LHI", "Australia/Lindeman", "Australia/Lord_Howe", 
				"Australia/Melbourne", "Australia/North", "Australia/NSW", "Australia/Perth", "Australia/Queensland", "Australia/South", "Australia/Sydney", 
				"Australia/Tasmania", "Australia/Victoria", "Australia/West", "Australia/Yancowinna", "Europe/Amsterdam", "Europe/Andorra", "Europe/Athens", 
				"Europe/Belfast", "Europe/Belgrade", "Europe/Berlin", "Europe/Bratislava", "Europe/Brussels", "Europe/Bucharest", "Europe/Budapest", "Europe/Chisinau", 
				"Europe/Copenhagen", "Europe/Dublin", "Europe/Gibraltar", "Europe/Guernsey", "Europe/Helsinki", "Europe/Isle_of_Man", "Europe/Istanbul", 
				"Europe/Jersey", "Europe/Kaliningrad", "Europe/Kiev", "Europe/Lisbon", "Europe/Ljubljana", "Europe/London", "Europe/Luxembourg", "Europe/Madrid", 
				"Europe/Malta", "Europe/Mariehamn", "Europe/Minsk", "Europe/Monaco", "Europe/Moscow", "Europe/Nicosia", "Europe/Oslo", "Europe/Paris", 
				"Europe/Podgorica", "Europe/Prague", "Europe/Riga", "Europe/Rome", "Europe/Samara", "Europe/San_Marino", "Europe/Sarajevo", "Europe/Simferopol", 
				"Europe/Skopje", "Europe/Sofia", "Europe/Stockholm", "Europe/Tallinn", "Europe/Tirane", "Europe/Tiraspol", "Europe/Uzhgorod", "Europe/Vaduz", 
				"Europe/Vatican", "Europe/Vienna", "Europe/Vilnius", "Europe/Volgograd", "Europe/Warsaw", "Europe/Zagreb", "Europe/Zaporozhye", "Europe/Zurich", 
				"Indian/Antananarivo", "Indian/Chagos", "Indian/Christmas", "Indian/Cocos", "Indian/Comoro", "Indian/Kerguelen", "Indian/Mahe", "Indian/Maldives", 
				"Indian/Mauritius", "Indian/Mayotte", "Indian/Reunion", "Pacific/Apia", "Pacific/Auckland", "Pacific/Chatham", "Pacific/Chuuk", "Pacific/Easter", 
				"Pacific/Efate", "Pacific/Enderbury", "Pacific/Fakaofo", "Pacific/Fiji", "Pacific/Funafuti", "Pacific/Galapagos", "Pacific/Gambier", 
				"Pacific/Guadalcanal", "Pacific/Guam", "Pacific/Honolulu", "Pacific/Johnston", "Pacific/Kiritimati", "Pacific/Kosrae", "Pacific/Kwajalein", 
				"Pacific/Majuro", "Pacific/Marquesas", "Pacific/Midway", "Pacific/Nauru", "Pacific/Niue", "Pacific/Norfolk", "Pacific/Noumea", "Pacific/Pago_Pago", 
				"Pacific/Palau", "Pacific/Pitcairn", "Pacific/Pohnpei", "Pacific/Ponape", "Pacific/Port_Moresby", "Pacific/Rarotonga", "Pacific/Saipan", 
				"Pacific/Samoa", "Pacific/Tahiti", "Pacific/Tarawa", "Pacific/Tongatapu", "Pacific/Truk", "Pacific/Wake", "Pacific/Wallis", "Pacific/Yap", 
				"Brazil/Acre", "Brazil/DeNoronha", "Brazil/East", "Brazil/West", "Canada/Atlantic", "Canada/Central", "Canada/East-Saskatchewan", "Canada/Eastern", 
				"Canada/Mountain", "Canada/Newfoundland", "Canada/Pacific", "Canada/Saskatchewan", "Canada/Yukon", "CET", "Chile/Continental", "Chile/EasterIsland", 
				"CST6CDT", "Cuba", "EET", "Egypt", "Eire", "EST", "EST5EDT", "Etc/GMT", "Etc/GMT+0", "Etc/GMT+1", "Etc/GMT+10", "Etc/GMT+11", "Etc/GMT+12", "Etc/GMT+2", 
				"Etc/GMT+3", "Etc/GMT+4", "Etc/GMT+5", "Etc/GMT+6", "Etc/GMT+7", "Etc/GMT+8", "Etc/GMT+9", "Etc/GMT-0", "Etc/GMT-1", "Etc/GMT-10", "Etc/GMT-11", 
				"Etc/GMT-12", "Etc/GMT-13", "Etc/GMT-14", "Etc/GMT-2", "Etc/GMT-3", "Etc/GMT-4", "Etc/GMT-5", "Etc/GMT-6", "Etc/GMT-7", "Etc/GMT-8", "Etc/GMT-9", 
				"Etc/GMT0", "Etc/Greenwich", "Etc/UCT", "Etc/Universal", "Etc/UTC", "Etc/Zulu", "Factory", "GB", "GB-Eire", "GMT", "GMT+0", "GMT-0", "GMT0", 
				"Greenwich", "Hongkong", "HST", "Iceland", "Iran", "Israel", "Jamaica", "Japan", "Kwajalein", "Libya", "MET", "Mexico/BajaNorte", "Mexico/BajaSur", 
				"Mexico/General", "MST", "MST7MDT", "Navajo", "NZ", "NZ-CHAT", "Poland", "Portugal", "PRC", "PST8PDT", "ROC", "ROK", "Singapore", "Turkey", "UCT", 
				"Universal", "US/Alaska", "US/Aleutian", "US/Arizona", "US/Central", "US/East-Indiana", "US/Eastern", "US/Hawaii", "US/Indiana-Starke", "US/Michigan", 
				"US/Mountain", "US/Pacific", "US/Pacific-New", "US/Samoa", "UTC", "W-SU", "WET", "Zulu"
			);
	}
	
	function getUTCZones() {
		return array(
				'UM12'		=> -12,
				'UM11'		=> -11,
				'UM10'		=> -10,
				'UM95'		=> -9.5,
				'UM9'		=> -9,
				'UM8'		=> -8,
				'UM7'		=> -7,
				'UM6'		=> -6,
				'UM5'		=> -5,
				'UM45'		=> -4.5,
				'UM4'		=> -4,
				'UM35'		=> -3.5,
				'UM3'		=> -3,
				'UM2'		=> -2,
				'UM1'		=> -1,
				'UTC'		=> 0,
				'UP1'		=> +1,
				'UP2'		=> +2,
				'UP3'		=> +3,
				'UP35'		=> +3.5,
				'UP4'		=> +4,
				'UP45'		=> +4.5,
				'UP5'		=> +5,
				'UP55'		=> +5.5,
				'UP575'		=> +5.75,
				'UP6'		=> +6,
				'UP65'		=> +6.5,
				'UP7'		=> +7,
				'UP8'		=> +8,
				'UP875'		=> +8.75,
				'UP9'		=> +9,
				'UP95'		=> +9.5,
				'UP10'		=> +10,
				'UP105'		=> +10.5,
				'UP11'		=> +11,
				'UP115'		=> +11.5,
				'UP12'		=> +12,
				'UP1275'	=> +12.75,
				'UP13'		=> +13,
				'UP14'		=> +14,
			);
	}
	function get_TimeZones_UTCZones_map() {
		$arr=array(
				    "Africa/Abidjan"=> "0",
				    "Africa/Accra"=> "0",
				    "Africa/Addis_Ababa"=> "+3",
				    "Africa/Algiers"=> "+1",
				    "Africa/Asmara"=> "+3",
				    "Africa/Bamako"=> "0",
				    "Africa/Bangui"=> "+1",
				    "Africa/Banjul"=> "0",
				    "Africa/Bissau"=> "0",
				    "Africa/Blantyre"=> "+2",
				    "Africa/Brazzaville"=> "+1",
				    "Africa/Bujumbura"=> "+2",
				    "Africa/Cairo"=> "+2",
				    "Africa/Casablanca"=> "0",
				    "Africa/Ceuta"=> "+1",
				    "Africa/Conakry"=> "+1",
				    "Africa/Dakar"=> "0",
				    "Africa/Dar_es_Salaam"=> "+3",
				    "Africa/Djibouti"=> "+3",
				    "Africa/Douala"=> "+1",
				    "Africa/El_Aaiun"=> "+1",
				    "Africa/Freetown"=> "0",
				    "Africa/Gaborone"=> "+2",
				    "Africa/Harare"=> "+2",
				    "Africa/Johannesburg"=> "+2",
				    "Africa/Juba"=> "+3",
				    "Africa/Kampala"=> "+3",
				    "Africa/Khartoum"=> "+3",
				    "Africa/Kigali"=> "+2",
				    "Africa/Kinshasa"=> "+1",
				    "Africa/Lagos"=> "+1",
				    "Africa/Libreville"=> "+1",
				    "Africa/Lome"=> "0",
				    "Africa/Luanda"=> "+1",
				    "Africa/Lubumbashi"=> "+5.5",
				    "Africa/Lusaka"=> "+2",
				    "Africa/Malabo"=> "+1",
				    "Africa/Maputo"=> "+2",
				    "Africa/Maseru"=> "+2",
				    "Africa/Mbabane"=> "+2",
				    "Africa/Mogadishu"=> "+3",
				    "Africa/Monrovia"=> "0",
				    "Africa/Nairobi"=> "+3",
				    "Africa/Ndjamena"=> "+1",
				    "Africa/Niamey"=> "+1",
				    "Africa/Nouakchott"=> "0",
				    "Africa/Ouagadougou"=> "0",
				    "Africa/Porto-Novo"=> "+1",
				    "Africa/Sao_Tome"=> "0",
				    "Africa/Timbuktu"=> "",
				    "Africa/Tripoli"=> "+2",
				    "Africa/Tunis"=> "+1",
				    "Africa/Windhoek"=> "+1",
				    "America/Adak"=> "-10",
				    "America/Anchorage"=> "-9",
				    "America/Anguilla"=> "-4",
				    "America/Antigua"=> "-4",
				    "America/Araguaina"=> "-3",
				    "America/Argentina/Buenos_Aires"=> "-3",
				    "America/Argentina/Catamarca"=> "-3",
				    "America/Argentina/ComodRivadavia"=> "",
				    "America/Argentina/Cordoba"=> "-3",
				    "America/Argentina/Jujuy"=> "-3",
				    "America/Argentina/La_Rioja"=> "-3",
				    "America/Argentina/Mendoza"=> "-3",
				    "America/Argentina/Rio_Gallegos"=> "-3",
				    "America/Argentina/Salta"=> "-3",
				    "America/Argentina/San_Juan"=> "-3",
				    "America/Argentina/San_Luis"=> "-4",
				    "America/Argentina/Tucuman"=> "-3",
				    "America/Argentina/Ushuaia"=> "-3",
				    "America/Aruba"=> "-4",
				    "America/Asuncion"=> "-4",
				    "America/Atikokan"=> "-5",
				    "America/Atka"=> "",
				    "America/Bahia"=> "-3",
				    "America/Bahia_Banderas"=> "-6",
				    "America/Barbados"=> "-4",
				    "America/Belem"=> "-3",
				    "America/Belize"=> "-6",
				    "America/Blanc-Sablon"=> "-4",
				    "America/Boa_Vista"=> "-4",
				    "America/Bogota"=> "-5",
				    "America/Boise"=> "-7",
				    "America/Buenos_Aires"=> "",
				    "America/Cambridge_Bay"=> "-7",
				    "America/Campo_Grande"=> "-4",
				    "America/Cancun"=> "-6",
				    "America/Caracas"=> "-4.5",
				    "America/Catamarca"=> "",
				    "America/Cayenne"=> "-3",
				    "America/Cayman"=> "-5",
				    "America/Chicago"=> "-6",
				    "America/Chihuahua"=> "-7",
				    "America/Coral_Harbour"=> "",
				    "America/Cordoba"=> "",
				    "America/Costa_Rica"=> "-6",
				    "America/Cuiaba"=> "-4",
				    "America/Curacao"=> "-4",
				    "America/Danmarkshavn"=> "0",
				    "America/Dawson"=> "-8",
				    "America/Dawson_Creek"=> "-7",
				    "America/Denver"=> "-7",
				    "America/Detroit"=> "-5",
				    "America/Dominica"=> "-4",
				    "America/Edmonton"=> "-7",
				    "America/Eirunepe"=> "-4",
				    "America/El_Salvador"=> "-6",
				    "America/Ensenada"=> "",
				    "America/Fort_Wayne"=> "",
				    "America/Fortaleza"=> "-3",
				    "America/Glace_Bay"=> "-4",
				    "America/Godthab"=> "-3",
				    "America/Goose_Bay"=> "-4",
				    "America/Grand_Turk"=> "-5",
				    "America/Grenada"=> "-4",
				    "America/Guadeloupe"=> "-4",
				    "America/Guatemala"=> "-6",
				    "America/Guayaquil"=> "-5",
				    "America/Guyana"=> "-4",
				    "America/Halifax"=> "-4",
				    "America/Havana"=> "-5",
				    "America/Hermosillo"=> "-7",
				    "America/Indiana/Indianapolis"=> "-5",
				    "America/Indiana/Knox"=> "-6",
				    "America/Indiana/Marengo"=> "-5",
				    "America/Indiana/Petersburg"=> "-5",
				    "America/Indiana/Tell_City"=> "-6",
				    "America/Indiana/Vevay"=> "-5",
				    "America/Indiana/Vincennes"=> "-5",
				    "America/Indiana/Winamac"=> "-5",
				    "America/Indianapolis"=> "",
				    "America/Inuvik"=> "-7",
				    "America/Iqaluit"=> "-5",
				    "America/Jamaica"=> "-5",
				    "America/Jujuy"=> "",
				    "America/Juneau"=> "-9",
				    "America/Kentucky/Louisville"=> "-5",
				    "America/Kentucky/Monticello"=> "-5",
				    "America/Knox_IN"=> "",
				    "America/Kralendijk"=> "-4",
				    "America/La_Paz"=> "-4",
				    "America/Lima"=> "-5",
				    "America/Los_Angeles"=> "-8",
				    "America/Louisville"=> "",
				    "America/Lower_Princes"=> "-4",
				    "America/Maceio"=> "-3",
				    "America/Managua"=> "-6",
				    "America/Manaus"=> "-4",
				    "America/Marigot"=> "-4",
				    "America/Martinique"=> "-4",
				    "America/Matamoros"=> "-6",
				    "America/Mazatlan"=> "-7",
				    "America/Mendoza"=> "",
				    "America/Menominee"=> "-6",
				    "America/Merida"=> "-6",
				    "America/Metlakatla"=> "-8",
				    "America/Mexico_City"=> "-6",
				    "America/Miquelon"=> "-3",
				    "America/Moncton"=> "-4",
				    "America/Monterrey"=> "-6",
				    "America/Montevideo"=> "-3",
				    "America/Montreal"=> "-5",
				    "America/Montserrat"=> "-4",
				    "America/Nassau"=> "-5",
				    "America/New_York"=> "-5",
				    "America/Nipigo"=> "-5",
				    "America/Nome"=> "-9",
				    "America/Noronha"=> "-2",
				    "America/North_Dakota/Beulah"=> "-6",
				    "America/North_Dakota/Center"=> "-6",
				    "America/North_Dakota/New_Salem"=> "-6",
				    "America/Ojinaga"=> "-7",
				    "America/Panama"=> "-5",
				    "America/Pangnirtung"=> "-5",
				    "America/Paramaribo"=> "-3",
				    "America/Phoenix"=> "-7",
				    "America/Port-au-Prince"=> "-5",
				    "America/Port_of_Spain"=> "-4",
				    "America/Porto_Acre"=> "",
				    "America/Porto_Velho"=> "-4",
				    "America/Puerto_Rico"=> "-4",
				    "America/Rainy_River"=> "-6",
				    "America/Rankin_Inlet"=> "-6",
				    "America/Recife"=> "-3",
				    "America/Regina"=> "-6",
				    "America/Resolute"=> "-6",
				    "America/Rio_Branco"=> "-4",
				    "America/Rosario"=> "",
				    "America/Santa_Isabel"=> "-8",
				    "America/Santarem"=> "-3",
				    "America/Santiago"=> "-4",
				    "America/Santo_Domingo"=> "-4",
				    "America/Sao_Paulo"=> "-3",
				    "America/Scoresbysund"=> "-1",
				    "America/Shiprock"=> "-7",
				    "America/Sitka"=> "-9",
				    "America/St_Barthelemy"=> "-4",
				    "America/St_Johns"=> "-3.5",
				    "America/St_Kitts"=> "-4",
				    "America/St_Lucia"=> "-4",
				    "America/St_Thomas"=> "-4",
				    "America/St_Vincent"=> "-4",
				    "America/Swift_Current"=> "-6",
				    "America/Tegucigalpa"=> "-6",
				    "America/Thule"=> "-4",
				    "America/Thunder_Bay"=> "-5",
				    "America/Tijuana"=> "-8",
				    "America/Toronto"=> "-5",
				    "America/Tortola"=> "-4",
				    "America/Vancouver"=> "-8",
				    "America/Virgin"=> "",
				    "America/Whitehorse"=> "-8",
				    "America/Winnipeg"=> "-6",
				    "America/Yakutat"=> "-9",
				    "America/Yellowknife"=> "-7",
				    "Antarctica/Casey"=> "+8",
				    "Antarctica/Davis"=> "+7",
				    "Antarctica/DumontDUrville"=> "+10",
				    "Antarctica/Macquarie"=> "+11",
				    "Antarctica/Mawson"=> "+5",
				    "Antarctica/McMurdo"=> "+12",
				    "Antarctica/Palmer"=> "-4",
				    "Antarctica/Rothera"=> "-3",
				    "Antarctica/South_Pole"=> "+12",
				    "Antarctica/Syowa"=> "+3",
				    "Antarctica/Vostok"=> "+6",
				    "Arctic/Longyearbyen"=> "+1",
				    "Asia/Aden"=> "+3",
				    "Asia/Almaty"=> "+6",
				    "Asia/Amman"=> "+2",
				    "Asia/Anadyr"=> "+12",
				    "Asia/Aqtau"=> "+5",
				    "Asia/Aqtobe"=> "+5",
				    "Asia/Ashgabat"=> "+5",
				    "Asia/Ashkhabad"=> "",
				    "Asia/Baghdad"=> "+3",
				    "Asia/Bahrain"=> "+3",
				    "Asia/Baku"=> "+4",
				    "Asia/Bangkok"=> "+7",
				    "Asia/Beirut"=> "+2",
				    "Asia/Bishkek"=> "+6",
				    "Asia/Brunei"=> "+8",
				    "Asia/Calcutta"=> "",
				    "Asia/Choibalsan"=> "+8",
				    "Asia/Chongqing"=> "+8",
				    "Asia/Chungking"=> "",
				    "Asia/Colombo"=> "+5.5",
				    "Asia/Dacca"=> "",
				    "Asia/Damascus"=> "+2",
				    "Asia/Dhaka"=> "+6",
				    "Asia/Dili"=> "+9",
				    "Asia/Dubai"=> "+4",
				    "Asia/Dushanbe"=> "+5",
				    "Asia/Gaza"=> "+2",
				    "Asia/Harbin"=> "+8",
				    "Asia/Hebron"=> "+2",
				    "Asia/Ho_Chi_Minh"=> "+7",
				    "Asia/Hong_Kong"=> "+8",
				    "Asia/Hovd"=> "+7",
				    "Asia/Irkutsk"=> "+9",
				    "Asia/Istanbul"=> "",
				    "Asia/Jakarta"=> "+7",
				    "Asia/Jayapura"=> "+9",
				    "Asia/Jerusalem"=> "+2",
				    "Asia/Kabul"=> "+4.5",
				    "Asia/Kamchatka"=> "+12",
				    "Asia/Karachi"=> "+5",
				    "Asia/Kashgar"=> "+8",
				    "Asia/Kathmandu"=> "+5.8",
				    "Asia/Katmandu"=> "",
				    "Asia/Kolkata"=> "+5.5",
				    "Asia/Krasnoyarsk"=> "+8",
				    "Asia/Kuala_Lumpur"=> "+8",
				    "Asia/Kuching"=> "+8",
				    "Asia/Kuwait"=> "+3",
				    "Asia/Macao"=> "",
				    "Asia/Macau"=> "+8",
				    "Asia/Magadan"=> "+12",
				    "Asia/Makassar"=> "+8",
				    "Asia/Manila"=> "+8",
				    "Asia/Muscat"=> "+4",
				    "Asia/Nicosia"=> "+2",
				    "Asia/Novokuznetsk"=> "+7",
				    "Asia/Novosibirsk"=> "+7",
				    "Asia/Omsk"=> "+7",
				    "Asia/Oral"=> "+5",
				    "Asia/Phnom_Penh"=> "+7",
				    "Asia/Pontianak"=> "+7",
				    "Asia/Pyongyang"=> "+9",
				    "Asia/Qatar"=> "+3",
				    "Asia/Qyzylorda"=> "+6",
				    "Asia/Rangoon"=> "+6.5",
				    "Asia/Riyadh"=> "+3",
				    "Asia/Saigon"=> "",
				    "Asia/Sakhalin"=> "+11",
				    "Asia/Samarkand"=> "+5",
				    "Asia/Seoul"=> "+9",
				    "Asia/Shanghai"=> "+8",
				    "Asia/Singapore"=> "+8",
				    "Asia/Taipei"=> "+8",
				    "Asia/Tashkent"=> "+5",
				    "Asia/Tbilisi"=> "+4",
				    "Asia/Tehran"=> "+3.5 ",
				    "Asia/Tel_Aviv"=> "",
				    "Asia/Thimbu"=> "",
				    "Asia/Thimphu"=> "+6",
				    "Asia/Tokyo"=> "+9",
				    "Asia/Ujung_Pandang"=> "",
				    "Asia/Ulaanbaatar"=> "+8",
				    "Asia/Ulan_Bator"=> "",
				    "Asia/Urumqi"=> "+8",
				    "Asia/Vientiane"=> "+7",
				    "Asia/Vladivostok"=> "+11",
				    "Asia/Yakutsk"=> "+10",
				    "Asia/Yekaterinburg"=> "+6",
				    "Asia/Yerevan"=> "+4",
				    "Atlantic/Azores"=> "-1",
				    "Atlantic/Bermuda"=> "-4",
				    "Atlantic/Canary"=> "0",
				    "Atlantic/Cape_Verde"=> "-1",
				    "Atlantic/Faeroe"=> "",
				    "Atlantic/Faroe"=> "0",
				    "Atlantic/Jan_Mayen"=> "",
				    "Atlantic/Madeira"=> "0",
				    "Atlantic/Reykjavik"=> "0",
				    "Atlantic/South_Georgia"=> "-2",
				    "Atlantic/St_Helena"=> "0",
				    "Atlantic/Stanley"=> "-3",
				    "Australia/ACT"=> "",
				    "Australia/Adelaide"=> "+9.5",
				    "Australia/Brisbane"=> "+10",
				    "Australia/Broken_Hill"=> "+9.5",
				    "Australia/Canberra"=> "",
				    "Australia/Currie"=> "+10",
				    "Australia/Darwin"=> "+9.5",
				    "Australia/Eucla"=> "+8.75",
				    "Australia/Hobart"=> "+10",
				    "Australia/LHI"=> "",
				    "Australia/Lindeman"=> "+10",
				    "Australia/Lord_Howe"=> "+10.5",
				    "Australia/Melbourne"=> "+10",
				    "Australia/North"=> "",
				    "Australia/NSW"=> "",
				    "Australia/Perth"=> "+8",
				    "Australia/Queensland"=> "",
				    "Australia/South"=> "",
				    "Australia/Sydney"=> "+10",
				    "Australia/Tasmania"=> "",
				    "Australia/Victoria"=> "",
				    "Australia/West"=> "",
				    "Australia/Yancowinna"=> "",
				    "Europe/Amsterdam"=> "+1",
				    "Europe/Andorra"=> "+1",
				    "Europe/Athens"=> "+2",
				    "Europe/Belfast"=> "",
				    "Europe/Belgrade"=> "+1",
				    "Europe/Berlin"=> "+1",
				    "Europe/Bratislava"=> "+1",
				    "Europe/Brussels"=> "+1",
				    "Europe/Bucharest"=> "+2",
				    "Europe/Budapest"=> "+1",
				    "Europe/Chisinau"=> "+2",
				    "Europe/Copenhagen"=> "+1",
				    "Europe/Dublin"=> "0",
				    "Europe/Gibraltar"=> "+1",
				    "Europe/Guernsey"=> "0",
				    "Europe/Helsinki"=> "+2",
				    "Europe/Isle_of_Man"=> "0",
				    "Europe/Istanbul"=> "+2",
				    "Europe/Jersey"=> "0",
				    "Europe/Kaliningrad"=> "+3",
				    "Europe/Kiev"=> "+2",
				    "Europe/Lisbon"=> "0",
				    "Europe/Ljubljana"=> "+1",
				    "Europe/London"=> "0",
				    "Europe/Luxembourg"=> "+1",
				    "Europe/Madrid"=> "+1",
				    "Europe/Malta"=> "+1",
				    "Europe/Mariehamn"=> "+2",
				    "Europe/Minsk"=> "+3",
				    "Europe/Monaco"=> "+1",
				    "Europe/Moscow"=> "+4",
				    "Europe/Nicosia"=> "",
				    "Europe/Oslo"=> "+1",
				    "Europe/Paris"=> "+1",
				    "Europe/Podgorica"=> "+1",
				    "Europe/Prague"=> "+1",
				    "Europe/Riga"=> "+2",
				    "Europe/Rome"=> "+1",
				    "Europe/Samara"=> "+4",
				    "Europe/San_Marino"=> "+1",
				    "Europe/Sarajevo"=> "+1",
				    "Europe/Simferopol"=> "+2",
				    "Europe/Skopje"=> "+1",
				    "Europe/Sofia"=> "+2",
				    "Europe/Stockholm"=> "+1",
				    "Europe/Tallinn"=> "+2",
				    "Europe/Tirane"=> "+1",
				    "Europe/Tiraspol"=> "",
				    "Europe/Uzhgorod"=> "+2",
				    "Europe/Vaduz"=> "+1",
				    "Europe/Vatican"=> "+1",
				    "Europe/Vienna"=> "+1",
				    "Europe/Vilnius"=> "+2",
				    "Europe/Volgograd"=> "+4",
				    "Europe/Warsaw"=> "+1",
				    "Europe/Zagreb"=> "+1",
				    "Europe/Zaporozhye"=> "+2",
				    "Europe/Zurich"=> "+1",
				    "Indian/Antananarivo"=> "+3",
				    "Indian/Chagos"=> "+6",
				    "Indian/Christmas"=> "+7",
				    "Indian/Cocos"=> "+6.5",
				    "Indian/Comoro"=> "+3",
				    "Indian/Kerguelen"=> "+5",
				    "Indian/Mahe"=> "+4",
				    "Indian/Maldives"=> "+5",
				    "Indian/Mauritius"=> "+4",
				    "Indian/Mayotte"=> "+3",
				    "Indian/Reunion"=> "+4",
				    "Pacific/Apia"=> "+13",
				    "Pacific/Auckland"=> "+12",
				    "Pacific/Chatham"=> "+12.75",
				    "Pacific/Chuuk"=> "+10",
				    "Pacific/Easter"=> "-6",
				    "Pacific/Efate"=> "+11",
				    "Pacific/Enderbury"=> "+13",
				    "Pacific/Fakaofo"=> "+14",
				    "Pacific/Fiji"=> "+12",
				    "Pacific/Funafuti"=> "+12",
				    "Pacific/Galapagos"=> "-6",
				    "Pacific/Gambier"=> "-9",
				    "Pacific/Guadalcana"=> "+11",
				    "Pacific/Guam"=> "+10",
				    "Pacific/Honolulu"=> "-10",
				    "Pacific/Johnston"=> "-10",
				    "Pacific/Kiritimati"=> "+14",
				    "Pacific/Kosrae"=> "+11",
				    "Pacific/Kwajalein"=> "+12",
				    "Pacific/Majuro"=> "+12",
				    "Pacific/Marquesas"=> "-9.5",
				    "Pacific/Midway"=> "-11",
				    "Pacific/Nauru"=> "+12",
				    "Pacific/Niue"=> "-11",
				    "Pacific/Norfolk"=> "+11.5",
				    "Pacific/Noumea"=> "+11",
				    "Pacific/Pago_Pago"=> "-11",
				    "Pacific/Palau"=> "",
				    "Pacific/Pitcairn"=> "-8",
				    "Pacific/Pohnpei"=> "+11",
				    "Pacific/Ponape"=> "",
				    "Pacific/Port_Moresby"=> "+10",
				    "Pacific/Rarotonga"=> "-10",
				    "Pacific/Saipan"=> "+10",
				    "Pacific/Samoa"=> "",
				    "Pacific/Tahiti"=> "-10",
				    "Pacific/Tarawa"=> "+12",
				    "Pacific/Tongatapu"=> "+13",
				    "Pacific/Truk"=> "",
				    "Pacific/Wake"=> "+12",
				    "Pacific/Wallis"=> "+12",
				    "Pacific/Yap"=> "",
				    "Brazil/Acre"=> "",
				    "Brazil/DeNoronha"=> "",
				    "Brazil/East"=> "",
				    "Brazil/West"=> "",
				    "Canada/Atlantic"=> "",
				    "Canada/Central"=> "",
				    "Canada/East-Saskatchewan"=> "",
				    "Canada/Eastern"=> "",
				    "Canada/Mountain"=> "",
				    "Canada/Newfoundland"=> "-3.5",
				    "Canada/Pacific"=> "",
				    "Canada/Saskatchewan"=> "",
				    "Canada/Yukon"=> "",
				    "CET"=> "",
				    "Chile/Continental"=> "",
				    "Chile/EasterIsland"=> "-6",
				    "CST6CDT"=> "",
				    "Cuba"=> "-5",
				    "EET"=> "+2",
				    "Egypt"=> "+2",
				    "Eire"=> "0",
				    "EST"=> "-5",
				    "EST5EDT"=> "-4",
				    "Etc/GMT"=> "",
				    "Etc/GMT+0"=> "",
				    "Etc/GMT+1"=> "",
				    "Etc/GMT+10"=> "",
				    "Etc/GMT+11"=> "",
				    "Etc/GMT+12"=> "",
				    "Etc/GMT+2"=> "",
				    "Etc/GMT+3"=> "",
				    "Etc/GMT+4"=> "",
				    "Etc/GMT+5"=> "",
				    "Etc/GMT+6"=> "",
				    "Etc/GMT+7"=> "",
				    "Etc/GMT+8"=> "",
				    "Etc/GMT+9"=> "",
				    "Etc/GMT-0"=> "",
				    "Etc/GMT-1"=> "",
				    "Etc/GMT-10"=> "",
				    "Etc/GMT-11"=> "",
				    "Etc/GMT-12"=> "",
				    "Etc/GMT-13"=> "",
				    "Etc/GMT-14"=> "",
				    "Etc/GMT-2"=> "",
				    "Etc/GMT-3"=> "",
				    "Etc/GMT-4"=> "",
				    "Etc/GMT-5"=> "",
				    "Etc/GMT-6"=> "",
				    "Etc/GMT-7"=> "",
				    "Etc/GMT-8"=> "",
				    "Etc/GMT-9"=> "",
				    "Etc/GMT0"=> "",
				    "Etc/Greenwich"=> "",
				    "Etc/UCT"=> "",
				    "Etc/Universal"=> "",
				    "Etc/UTC"=> "",
				    "Etc/Zulu"=> "",
				    "Factory"=> "",
				    "GB"=> "+5.5",
				    "GB-Eire"=> "",
				    "GMT"=> "0",
				    "GMT+0"=> "0",
				    "GMT-0"=> "0",
				    "GMT0"=> "0",
				    "Greenwich"=> "",
				    "Hongkong"=> "+8",
				    "HST"=> "-10",
				    "Iceland"=> "0",
				    "Iran"=> "+3.5",
				    "Israel"=> "+2",
				    "Jamaica"=> "-5",
				    "Japan"=> "+9",
				    "Kwajalein"=> "+12",
				    "Libya"=> "+2",
				    "MET"=> "+01",
				    "Mexico/BajaNorte"=> "-08",
				    "Mexico/BajaSur"=> "",
				    "Mexico/General"=> "+5.5",
				    "MST"=> "- 7",
				    "MST7MDT"=> "",
				    "Navajo"=> "",
				    "NZ"=> "+12",
				    "NZ-CHAT"=> "",
				    "Poland"=> "+1",
				    "Portugal"=> "0",
				    "PRC"=> "08",
				    "PST8PDT"=> "-7",
				    "ROC"=> "+8",
				    "ROK"=> "+9",
				    "Singapore"=> "+8",
				    "Turkey"=> "+2",
				    "UCT"=> "0",
				    "US/Mountain"=> "",
				    "US/Pacific"=> "",
				    "US/Pacific-New"=> "-7",
				    "US/Samoa"=> "",
				    "UTC"=> "",
				    "W-SU"=> "+4",
				    "WET"=> "+ 1",
				    "Zulu"=> "0"
			);
		return $arr;
	}
}
?>
